### ISSUE TITLE
Compatibility with older Android versions (4.1) ?

### ISSUE THREAD

**Issue by Gullumluvl** [GEANT/CAT-Android#45]
Hi,
first I am sorry to be a careless person using such outdated and therefore insecure OS version, however I can't immediately upgrade now.

Is there a way to make the app compatible with Android 4.1 with little work? I have zero Android development skills, nor Java knowledge, so I don't know how to proceed and I understand that this is not a priority.

For the record, I have tried installing the Android 4.3 apk and directly got an error message "Problem while analysing the whole" or equivalent (translated from my language).

Alternatively, can't we just extract the relevant information from the XML Config file itself to configure it without any app? What else would we need after base64 decoding the server side certificates?

**Comment by restena-sw** [comment]
First off, thanks for your realisation that running Android 4.1 is a terrible idea these days.

The app has a minimum requirement of 4.3 for real operational reasons. Android introduced the necessary API calls for secure device configuration only with that version.

The .apk has the minimum requirement of 4.3 built-in in its so-called "manifest". That's why the attempt to install it on a lower version fails. Even if that constraint wasn't there, it would fail in the moment you try the actual installation of the config because the API calls are missing.

You can also not configure Android 4.1 securely manually because that version did not allow to configure the server name, only the CA. In general, this is insufficient for a proper security level.

I.e. there is literally nothing you can do to make this work in a secure way. Sorry.
